import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { React } from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Git Timeline",
  description: "Generated by create next app to create your next git timeline :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen"}>{children}</body>
    </html>
  );
}
